In [1]:
import numpy as np

1. Basic Operations:

In [2]:
arr=np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
arr2=np.random.rand(3,3)#here we are creating a 2d array with 3 and 3 
print(arr2)

[[0.64423486 0.84082805 0.41283742]
 [0.16014181 0.95052178 0.24899689]
 [0.42259927 0.93969172 0.11300156]]


In [3]:
identity_matrix=np.eye(3)# eye function is used to create a 2d array with ones on the diagonal and zeros elsewhere
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
identity_matrix2=np.eye(3,k=1)#here we have to create a identity matrix of size 3 x 3 with main diagonal shifted by 1
print(identity_matrix2)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


2. Array Manipulations:

In [6]:
arr_1d=np.arange(6)
print(arr_1d)
#reshaping hr array from 1d to 2d
arr_2d=np.reshape(arr_1d,(3,2))
print(arr_2d)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [7]:
#now we will have to flatten the arr_2d to arr1d.
arr1d_flatten=arr_2d.flatten()
print(arr1d_flatten)

[0 1 2 3 4 5]


In [8]:
aarray=np.array([1,2,3,3,4,5,6,7])
Aarray=np.array([20,3,0,44,2,22])
#here we are going to concatenate.
concatenated_array=np.concatenate((aarray,Aarray))
print(concatenated_array)

[ 1  2  3  3  4  5  6  7 20  3  0 44  2 22]


In [9]:
# Create a 2D array
array_2d = np.array([[0, 1, 2, 3],
                     [4, 5, 6, 7],
                     [8, 9, 10, 11]])

# Extract the elements of the second row
second_row = array_2d[1]
print(second_row)

[4 5 6 7]


In [10]:
# Extract the elements of the third column
third_column = array_2d[:, 2]
print(third_column)

[ 2  6 10]


In [11]:
# Create a 4x4 matrix
matrix_4x4 = np.array([[ 1,  2,  3,  4],
                       [ 5,  6,  7,  8],
                       [ 9, 10, 11, 12],
                       [13, 14, 15, 16]])

# Extract a 2x2 sub-matrix from the center
sub_matrix = matrix_4x4[1:3, 1:3]
print(sub_matrix)

[[ 6  7]
 [10 11]]


3. Mathematical Operations:

In [12]:
operation_array1=np.array([[1,2,3],[4,5,6]])
operation_array2=np.array([[7,8,9],[10,11,12]])

# element addition
addition_matrix=operation_array1+operation_array2
print(addition_matrix)

# element subtraction
subtraction_matrix=operation_array1-operation_array2
print(subtraction_matrix)

# element multiplication
multiplication_matrix=operation_array1*operation_array2
print(multiplication_matrix)

# element division
division_matrix=operation_array1/operation_array2
print(division_matrix)

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 7 16 27]
 [40 55 72]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [13]:
# Create an array of numbers
array = np.array([1, 2, 3, 4, 5])

# Calculate sum
sum_array = np.sum(array)
print("Sum of elements:", sum_array)

# Calculate mean
mean_array = np.mean(array)
print("Mean of elements:", mean_array)

# Calculate standard deviation
std_dev_array = np.std(array)
print("Standard deviation of elements:", std_dev_array)


Sum of elements: 15
Mean of elements: 3.0
Standard deviation of elements: 1.4142135623730951


In [14]:
# Create a random 2D array of shape (5, 5)
array_2d = np.random.randint(1, 10, size=(5, 5))
print(array_2d)

# Compute sum along each row
sum_along_rows = np.sum(array_2d, axis=1)
print(sum_along_rows)

# Compute sum along each column
sum_along_columns = np.sum(array_2d, axis=0)
print(sum_along_columns)


[[5 6 2 4 4]
 [6 7 4 9 7]
 [9 2 5 8 2]
 [9 6 5 2 6]
 [9 5 4 2 7]]
[21 33 26 28 27]
[38 26 20 25 26]


In [15]:
# Generate a random array of shape (5, 5)
random_array = np.random.randint(1, 50, size=(5, 5))
print("\nRandom Array:")
print(random_array)

# Sort along rows
sorted_rows = np.sort(random_array, axis=1)
print("\nSorted along rows:")
print(sorted_rows)

# Sort along columns
sorted_columns = np.sort(random_array, axis=0)
print("\nSorted along columns:")
print(sorted_columns)



Random Array:
[[45 42 43 19 47]
 [16 48  6 39  3]
 [19 41 27 31 42]
 [17 33 44  8 41]
 [38 18 43 33  2]]

Sorted along rows:
[[19 42 43 45 47]
 [ 3  6 16 39 48]
 [19 27 31 41 42]
 [ 8 17 33 41 44]
 [ 2 18 33 38 43]]

Sorted along columns:
[[16 18  6  8  2]
 [17 33 27 19  3]
 [19 41 43 31 41]
 [38 42 43 33 42]
 [45 48 44 39 47]]


In [16]:
# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Create a 1D array to add to each row
add_array = np.array([10, 20, 30])

# Use broadcasting to add add_array to each row of array_2d
result_array = array_2d + add_array[:, np.newaxis]
print(result_array)



Resulting 2D array after broadcasting:
[[11 12 13]
 [24 25 26]
 [37 38 39]]
